name: health_fitness
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.62.0
  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.6.2
  intl: ^0.18.1

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  pedometer:
  permission_handler:
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  health: ^8.1.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  workmanager: ^0.5.2
  rxdart: ^0.27.7
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700
