// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TiDfMfkGgiPuuXZQigJMOZwQpmqRqUU',
    appId: '1:96843346440:web:b27ac5ffc08941749bd7bd',
    messagingSenderId: '96843346440',
    projectId: 'health-fitness-23e8b',
    authDomain: 'health-fitness-23e8b.firebaseapp.com',
    storageBucket: 'health-fitness-23e8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6sWnhhdnM3f8HUuJRSfaK1wK6Ae7YQk',
    appId: '1:96843346440:android:464eea2184be389c9bd7bd',
    messagingSenderId: '96843346440',
    projectId: 'health-fitness-23e8b',
    storageBucket: 'health-fitness-23e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpPFBxU1yeILu6tqCrF45-Y-tcYcZx6c',
    appId: '1:96843346440:ios:e8c1102dd2b325f89bd7bd',
    messagingSenderId: '96843346440',
    projectId: 'health-fitness-23e8b',
    storageBucket: 'health-fitness-23e8b.appspot.com',
    iosBundleId: 'com.example.healthFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpPFBxU1yeILu6tqCrF45-Y-tcYcZx6c',
    appId: '1:96843346440:ios:e8c1102dd2b325f89bd7bd',
    messagingSenderId: '96843346440',
    projectId: 'health-fitness-23e8b',
    storageBucket: 'health-fitness-23e8b.appspot.com',
    iosBundleId: 'com.example.healthFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7TiDfMfkGgiPuuXZQigJMOZwQpmqRqUU',
    appId: '1:96843346440:web:e2e27e6f933d40399bd7bd',
    messagingSenderId: '96843346440',
    projectId: 'health-fitness-23e8b',
    authDomain: 'health-fitness-23e8b.firebaseapp.com',
    storageBucket: 'health-fitness-23e8b.appspot.com',
  );
}
